flaskassignment/admin/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request
from flaskassignment import bcrypt, db, app
from flaskassignment.admin.forms import AdminLogin, AdminUpdateEmployee, SearchForm
from flask_login import login_user, logout_user, login_required
from flaskassignment.models import Employee
from flaskassignment.employee.forms import RegisterEmployee
from flask_login import current_user
import requests
import jwt


admin = Blueprint("admin", __name__)


@admin.route("/")
def home():
    if current_user.is_authenticated:
        if current_user.is_admin:
            data = Employee.query.all()
            return render_template("admin_home.html", title="HOME", data=data)
        else:
            return redirect(url_for("employee.home"))
    else:
        return redirect(url_for("admin.admin_login"))


@admin.route('/admin_login', methods=['GET', 'POST'])
def admin_login():
    form = AdminLogin()
    if form.validate_on_submit():
        admins = Employee.query.filter_by(email=form.email.data).first()
        if admins and bcrypt.check_password_hash(admins.password, form.password.data) and admins.is_admin:
            login_user(admins, remember=form.remember.data)
            flash('User Successfully Logged In !', 'success')
            app.logger.info('%s Logged in Successful', admins.email)
            return redirect(url_for('admin.home'))
        else:
            app.logger.info('%s Logged in Unuccessful', admins.email)
            flash('Login Failed. Either detail is wrong', 'danger')
    return render_template("admin_login.html", title="Admin Login", form=form)


@admin.route('/add_new_employee', methods=['GET', 'POST'])
@login_required
def add_new_employee():
    if current_user.is_admin:
        if current_user.is_authenticated:
            form = RegisterEmployee()
            if form.validate_on_submit():
                hashed_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
                employee = Employee(first_name=form.first_name.data, last_name=form.last_name.data,
                                    email=form.email.data, password=hashed_pass, phone_num=form.phone_num.data,
                                    dob=form.dob.data, address=form.address.data)
                db.session.add(employee)
                db.session.commit()
                app.logger.info('%s employee created Successfully created by Admin %s', employee.email, current_user.email)
                flash('Account Created for {}!'.format(form.first_name.data), 'success')
                return redirect(url_for('admin.home'))
            return render_template("register_new_employee.html",
                                   title="Register New Employee", form=form)
        else:
            return redirect(url_for("main.home"))
    else:
        return redirect(url_for("employee.home"))


@admin.route("/update_employee/<int:employee_id>", methods=['GET', 'POST'])
@login_required
def update_employee(employee_id):
    if current_user.is_admin:
        if current_user.is_authenticated:
            employee = Employee.query.get_or_404(employee_id)
            if not employee.is_admin:
                form = AdminUpdateEmployee()
                if form.validate_on_submit():
                    employee.first_name = form.first_name.data
                    employee.last_name = form.last_name.data
                    employee.dob = form.dob.data
                    employee.address = form.address.data
                    db.session.commit()
                    app.logger.info('%s employee Successfully updated by Admin %s', employee.email, current_user.email)
                    flash('User Successfully Updated!', 'success')
                    return redirect(url_for('admin.home'))
                elif request.method == 'GET':
                    form.first_name.data = employee.first_name
                    form.last_name.data = employee.last_name
                    form.dob.data = employee.dob
                    form.address.data = employee.address
                return render_template("update_employee.html", title="Update Employee", form=form, employee_id=employee_id)
            else:
                return redirect(url_for("admin.home"))
        else:
            return redirect(url_for("main.home"))
    else:
        return redirect(url_for("employee.home"))


@admin.route("/delete_employee/<int:employee_id>", methods=['POST'])
@login_required
def delete_employee(employee_id):
    if current_user.is_admin:
        if current_user.is_authenticated:
            employee = Employee.query.get_or_404(employee_id)
            app.logger.info('%s employee Deleted Successfully by Admin %s', employee.email, current_user.email)
            db.session.delete(employee)
            db.session.commit()
            return redirect(url_for('admin.home'))
        else:
            return redirect(url_for("main.home"))
    else:
        return redirect(url_for("employee.home"))


@admin.route('/logout')
def logout():
    if current_user.is_admin:
        app.logger.info('%s Admin successfully logged out', current_user.email)
        logout_user()
        return redirect(url_for('main.home'))
    else:
        return redirect(url_for("employee.home"))


@admin.route("/search", methods=['GET', 'POST'])
@login_required
def search_employee():
    if current_user.is_admin:
        form = SearchForm()
        if current_user.is_authenticated and current_user.is_admin:
            data = {
                'email': current_user.email,
                'data': form.search_value.data
            }
            employee = {}
            flag = False
            if request.method == 'POST':
                app.logger.info('%s Admin searched with variable %s', current_user.email, form.search_value.data)
                token = {"token": jwt.encode(data, app.config.get('SECRET_KEY')).decode('UTF-8')}
                employee = requests.get("http://127.0.0.1:5000/api/search_result", params=token).json()
                flag = True
            return render_template("search.html", title="Search Employee", form=form, data=employee, flag=flag)
        else:
            return redirect(url_for("admin.home"))
    else:
        return redirect(url_for("employee.home"))

flaskassignment/employee/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request
from flaskassignment import bcrypt, db, app
from flaskassignment.models import Employee
from flaskassignment.employee.forms import RegisterEmployee, Login, UpdateEmployee
from flask_login import login_user, logout_user, current_user, login_required


employee = Blueprint('employee', __name__)


@employee.route("/")
def home():
    return redirect(url_for("employee.employee_details"))


@employee.route("/register_employee", methods=['GET', 'POST'])
def register_employee():
    if current_user.is_authenticated:
        return redirect(url_for('employee.employee_details'))
    form = RegisterEmployee()
    if form.validate_on_submit():
        hashed_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        employe = Employee(first_name=form.first_name.data, last_name=form.last_name.data,
                                email=form.email.data, password=hashed_pass, phone_num=form.phone_num.data,
                                dob=form.dob.data, address=form.address.data)
        db.session.add(employe)
        db.session.commit()
        app.logger.info('%s Successfully Registered', employe.email)
        flash('Account Created for {}!'.format(form.first_name.data), 'success')
        return redirect(url_for('employee.login'))
    return render_template("register_employee.html",
                               title="Register Employee", form=form)


@employee.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = Login()
    if form.validate_on_submit():
        employe = Employee.query.filter_by(email=form.email.data).first()
        if employe and bcrypt.check_password_hash(employe.password, form.password.data) and not employe.is_admin:
            login_user(employe, remember=form.remember.data)
            app.logger.info('%s Logged in Successfully', employe.email)
            flash('User Successfully Logged In !', 'success')
            return redirect(url_for('employee.employee_details'))
        else:
            app.logger.info('%s Logged in Unsuccessful', employe.email)
            flash('Login Failed. Either detail is wrong', 'danger')

    return render_template("login.html",
                               title="Login Employee", form=form)


@employee.route('/logout')
def logout():
    if not current_user.is_admin:
        app.logger.info('%s Successfully Logged Out', current_user.email)
        logout_user()
        return redirect(url_for('main.home'))
    else:
        return redirect(url_for("admin.home"))


@employee.route('/employee_details', methods=['GET', 'POST'])
@login_required
def employee_details():
    if not current_user.is_admin:
        form = UpdateEmployee()
        if form.validate_on_submit():
            current_user.first_name = form.first_name.data
            current_user.last_name = form.last_name.data
            current_user.phone_num = form.phone_num.data
            current_user.dob = form.dob.data
            current_user.address = form.address.data
            db.session.commit()
            app.logger.info('%s Updated its own details', current_user.email)
            flash('User Successfully Updated!', 'success')
            return redirect(url_for('employee.employee_details'))
        elif request.method == 'GET':
            form.first_name.data = current_user.first_name
            form.last_name.data = current_user.last_name
            form.phone_num.data = current_user.phone_num
            form.dob.data = current_user.dob
            form.address.data = current_user.address
        return render_template("employee_details.html", title="Employee Details", form=form)
    else:
        return redirect(url_for("admin.home"))

flaskassignment/main/routes.py
from flask import Blueprint
from flask import render_template


main = Blueprint("main", __name__)


@main.route("/")
def home():
    return render_template("home.html", title="HOME")


@main.route("/about")
def about():
    return render_template("about.html", title="ABOUT")

flaskassignment/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-2 m-5 bg-white font-italic border rounded">
        <h1> This is the About Page Information related to the website can be posted here.......</h1>
    </div>
{% endblock %}

flaskassignment/templates/admin_home.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-2 m-5 bg-white border rounded">
        {% if current_user.is_authenticated %}
            <div class="p-2 m-2">
                <a href="{{ url_for('admin.add_new_employee') }}" class="btn btn-primary p-2 m-1">
                    Add New Employee
                </a>
                <a href="{{ url_for('admin.search_employee') }}" class="btn btn-primary p-2 m-1 ">
                    Search Employee
                </a>
            </div>
        <div class="row p-2 m-2">
                {% for user in data %}
                    {% if user.is_admin %}
                    {% else %}
                        <a href="{{ url_for('admin.update_employee', employee_id=user.id) }}">
                            <h1>{{ user.first_name }}  {{ user.last_name }}</h1>
                            <h1>{{ user.email }}</h1>
                        </a>
                        <hr>
                    {% endif %}
                {% endfor %}
            </div>
        {% else %}
            <h1> Hello, welcome to our page </h1>
        {% endif %}
        </div>
{% endblock %}

flaskassignment/templates/admin_login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-2 m-5 bg-white border rounded">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class="form-group p-2">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control") }}
                {% endif %}
            </div>
             <div class="form-group p-2">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group mx-2 form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
            <div class="py-3 px-2 form-group">
                {{ form.submit(class="btn btn-primary form-control") }}
            </div>
        </form>
    </div>
{% endblock %}

flaskassignment/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css">
    {% if title %}
        <title> {{ title }} </title>
    {% else %}
        <title> Assignment </title>
    {% endif %}
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.min.js" ></script>
</head>
<body class="bg-light">
    <nav class="p-2 navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        {% if current_user.is_authenticated %}
            {% if current_user.is_admin %}
                <a class="navbar-brand" href="{{ url_for('admin.home') }}">Home</a>
            {% else %}
                <a class="navbar-brand" href="{{ url_for('employee.home') }}">Home</a>
            {% endif %}
        {% else %}
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Home</a>
        {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                {% if current_user.is_authenticated  %}
                    <a class="nav-item nav-link" href="{{ url_for('employee.employee_details') }}">Profile</a>
                    {% if current_user.is_admin %}
                        <a class="nav-item nav-link" href="{{ url_for('admin.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('employee.logout') }}">Logout</a>
                    {% endif %}
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('employee.register_employee') }}">Register</a>
                    <a class="nav-item nav-link" href="{{ url_for('employee.login') }}"> Employee Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('admin.admin_login') }}"> Admin Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category,message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block content %}
    {% endblock %}
</body>
</html>

flaskassignment/templates/employee_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-2 m-5 bg-white border rounded">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class="form-group p-2">
                {{ form.first_name.label(class="form-control-label") }}
                {% if form.first_name.errors %}
                    {{ form.first_name(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.first_name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.first_name(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group p-2">
                {{ form.last_name.label(class="form-control-label")  }}
                {% if form.last_name.errors %}
                    {{ form.last_name(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.last_name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.last_name(class="form-control form-control") }}
                {% endif %}
            </div>
            <div class="form-group p-2">
                {{ form.phone_num.label(class="form-control-label")  }}
                {% if form.phone_num.errors %}
                    {{ form.phone_num(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.phone_num.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.phone_num(class="form-control form-control") }}
                {% endif %}
            </div>
            <div class="form-group p-2">
                {{ form.dob.label(class="form-control-label")  }}
                {% if form.dob.errors %}
                    {{ form.dob(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.dob.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.dob(class="form-control form-control") }}
                {% endif %}
            </div>
            <div class="form-group p-2">
                {{ form.address.label(class="form-control-label")  }}
                {% if form.address.errors %}
                    {{ form.address(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.address.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.address(class="form-control form-control") }}
                {% endif %}
            </div>
            <div class="py-3 px-2 form-group">
                {{ form.submit(class="btn btn-primary form-control") }}
            </div>
{% endblock %}

flaskassignment/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-2 m-5 bg-white font-italic border rounded">
        <div class="row">
            <h1>
                Hello This is our Home Page!!!!!
                <p>Update with any info that you want</p>
            </h1>
        </div>
    </div>
{% endblock %}

flaskassignment/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-2 m-5 bg-white border rounded">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class="form-group p-2">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control") }}
                {% endif %}
            </div>
             <div class="form-group p-2">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group mx-2 form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
            <div class="py-3 px-2 form-group">
                {{ form.submit(class="btn btn-primary form-control") }}
            </div>
        </form>
        <small class="text-muted px-2">
            Need an account?
            <a href="{{ url_for('employee.register_employee') }}"> Sign Up</a>
        </small>
    </div>
{% endblock %}

flaskassignment/templates/logout.html
{% extends 'base.html' %}

{% block content %}
    <h1> This is the About Page Information related to the website can be posted here.</h1>
{% endblock %}

flaskassignment/templates/search.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-2 m-5 bg-white border rounded">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class="form-group p-2">
                {{ form.search_value.label(class="form-control-label") }}
                {% if form.search_value.errors %}
                    {{ form.search_value(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.search_value.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.search_value(class="form-control") }}
                {% endif %}
            </div>
            <div class="py-3 px-2 form-group">
                {{ form.submit(class="btn btn-primary form-control") }}
            </div>
        </form>
        <legend class="row p-2 m-2">
            <h1>RESULTS</h1>
            <hr>
        </legend>
        <div class="row p-2 m-2">
            {% if flag %}
                {% for key in data %}
                    <a href="{{ url_for('admin.update_employee', employee_id=data[key]['id']) }}">
                        <h1>{{ data[key]['first_name'] }}  {{ data[key]['last_name'] }}</h1>
                        <h1>{{ data[key]['email'] }}</h1>
                    </a>
                    <hr>
                {% endfor %}
            {% else %}
            {% endif %}
        </div>
    </div>
{% endblock %}

flaskassignment/templates/update_employee.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-2 m-5 bg-white border rounded">
        <div class="row">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <div class="form-group p-2">
                    {{ form.first_name.label(class="form-control-label") }}
                    {% if form.first_name.errors %}
                        {{ form.first_name(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.first_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.first_name(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group p-2">
                    {{ form.last_name.label(class="form-control-label")  }}
                    {% if form.last_name.errors %}
                        {{ form.last_name(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.last_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.last_name(class="form-control form-control") }}
                    {% endif %}
                </div>
                <div class="form-group p-2">
                    {{ form.dob.label(class="form-control-label")  }}
                    {% if form.dob.errors %}
                        {{ form.dob(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.dob.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.dob(class="form-control form-control") }}
                    {% endif %}
                </div>
                <div class="form-group p-2">
                    {{ form.address.label(class="form-control-label")  }}
                    {% if form.address.errors %}
                        {{ form.address(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.address.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.address(class="form-control form-control") }}
                    {% endif %}
                </div>
                <div class="col-md-2 py-2 mx-2">
                    {{ form.submit(class="btn btn-primary form-control") }}
                </div>
                <div class="col-md-2 py-2 mx-2">
                    <button type="button" class="btn btn-danger form-control" data-toggle="modal" data-target="#DeleteModal">Delete Employee</button>
                </div>
            </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="DeleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="DeleteModalLabel">Delete Employee?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('admin.delete_employee', employee_id=employee_id) }}" method="POST">
                  <input class="btn btn-danger" type="submit" value="Delete">
              </form>
          </div>
        </div>
      </div>
    </div>

{% endblock %}